dist: xenial
language: java
jdk:
- openjdk10
deploy:
  provider: releases
  skip_cleanup: true
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - build/libs/shortener*
  - src/main/resources/application.properties
  on:
    repo: apardyl/url-shortener
    tags: true
    branch: master
